### ISSUE TITLE
Does stacks return `sizes` for objects that aren't available?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/digital_stacks_rails#1]
see: https://stacks.stanford.edu/image/iiif/rx795tx1655%2F00004472/info.json

Those sizes aren't actually available to anyone. Where should we handle this?

Related to https://github.com/sul-dlss/sul-embed/issues/295

**Comment by cbeer** [comment]
I think I dealt with that already. If the image is no-download, this code only returns the thumbnail size.

**Comment by mejackreed** [comment]
Ok thats great, thanks!
