### ISSUE TITLE
When a user requests the download of a file, the content-headers should add the actual filename and ask the browser to download instead of render

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/digital_stacks_rails#16]
Use case:  when a user requests the download of a Revs image, the browser used to provide a "save as" box with the actual filename from the stacks.  This is desirable since the filenames are an important file differentiator, particularly when downloading many files (often times the filename includes things like the sourceID or other identifier).

The new IIIF implementation makes all filenames "default.X" (e.g. default.jpg) and also renders straight in the browser, requiring the user to take additional actions to save the image.  It looks like there is already an "action=download" querystring parameter being passed to the server, can this be acted upon to change the behavior appropriately?

**Comment by peetucket** [comment]
Ben asked me to spam all of you by tagging this ticket.  Blame Canada.  @blalbrit @LynnMcRae @azaroth42 @rosy1280

**Comment by blalbrit** [comment]
@cbeer We'll want to have a conversation about this when you get back, so that we get a plan in place.

**Comment by azaroth42** [comment]
And (IMO) the implementation is to test if action=download is being passed as a query param, and if so then add the response header:  
```
Content-Disposition: attachment;filename={identifier}.{format}
```

If the image being requested does not have the IIIF region param of `full`, then the filename should be `{identifier}-region.{format}`.  I don't think we need to care about rotation (unlikely to ever be not 0), mirroring (unlikely to want both mirrored and non-mirrored separately), quality (unlikely to want anything other than the best) or size (unlikely to want anything other than the highest available).

**Comment by peetucket** [comment]
Thanks @azaroth42   Looks like the requested image size already appears in the request url ?  e.g. look at https://purl.stanford.edu/cs153nc2025 and see the options that are available for download.  Each download should have the same filename, represent the full image, but be presented with different dimensions.  I agree just downloading the largest possible is the most likely scenario (client can always downsample) but that would change the current behavior of offering multiple sizes at download time.

**Comment by azaroth42** [comment]
@peetucket: Right, the download would have the same filename, being `{identifier}.{format}` regardless of which size they got. So you wouldn't be able to naively download all three (say) without first renaming or moving them. Or if you're happy with the browser's default behavior for multiple downloads with the same filename (such as renaming to `{identifier} ({n}).{format}`)

**Comment by peetucket** [comment]
@azaroth42 sounds good - same filename each time is totally fine, the OS/browser can deal with clashing filenames in the unlikely case the user downloads multiple sizes
