### ISSUE TITLE
Create media controller in stacks rails app

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/digital_stacks_rails#27]

**Comment by LynnMcRae** [comment]
There is work this controller will need to do that is identical to /file and /image, specifically to invoke dor-rights-auth to see if the file is not world-accessible and to redirect the user through a stacks/auth/media path for webauth.   Hopefully /file and /image already show us how to share that logic across content controllers.  The unique aspects of /media will be the subsequent token minting and media specific redirects.

**Comment by ndushay** [comment]
I have pushed up a `media_controller` branch of digital_stacks_rails   https://github.com/sul-dlss/digital_stacks_rails/tree/media-controller.

It is by no means ready to ship, but it does have passing tests for ensuring the expected things happen for rights stuff:  cancan will allow an authenticated user through;  the app will not let a restricted file out, etc.    It currently serves out the playlist file when it gets a request for mp4 format.

Some of the work remaining (probably for other ticket):

- [ ] beef up access/restricted tests, in general (more cases)
- [ ] implement (whatever we decide) for show action
- [ ] add in the pair tree druid stuff for streaming url
- [ ] deal with dash streaming type in addition to hls for mp4
- [ ] deal with mp3, mov and other formats in addition to mp4

**Comment by ndushay** [comment]
opening new ticket for remaining work
