### ISSUE TITLE
Implement generation/validation of media token in stacks

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/digital_stacks_rails#28]
Take advantage of existing IIIF token minting code or implement new method.

may require some aliasing or renaming of existing methods, as well as determining if it has necessary functions like token expiration.

**Comment by LynnMcRae** [comment]
See also #31

**Comment by ndushay** [comment]
Current code in digital_stacks_rails does include expiration (currently set to 1.hour.from_now ):

https://github.com/sul-dlss/digital_stacks_rails/blob/master/app/controllers/iiif_token_controller.rb#L40-50

```ruby
  def write_bearer_token_cookie(token)
    # webauth users already have a webauth cookie; no additional cookie needed
    return if current_user.webauth_user?

    cookies[:bearer_token] = {
      value: token,
      expires: 1.hour.from_now,
      httponly: true,
      secure: request.ssl?
    }
 end
```
