### ISSUE TITLE
Media stacks - Evaluate manifest/playlist redirects in stacks

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/digital_stacks_rails#29]
Evaluate how to redirect playlist M3U8 and manifest (MPD) to wowza server from stacks URL based on user's browser

we need to support two types of manifest files since varying client support requires it

Also:  Evaluate whether difference between HLS and MPEG-dash is important 

HLS and MPEG-dash both make HTTP requests for the manifest, but

HLS makes HTTP range queries to get it in chunks

MPEG-dash has the client make TCP connections to get data

**Comment by LynnMcRae** [comment]
This needs to be part of the complete specification of the stacks/media URL syntax. So far this is the only addition to the URL beyond identifying the object and resource desired but we don't know if that's all we need

**Comment by ndushay** [comment]
We think this is Rails level work, rather than Apache level work.

**Comment by peetucket** [comment]
possibly related to/duplicates #29

**Comment by ndushay** [comment]
#33 is closed;  leaving this open until we have dash format working in the tracer bullet.
