### ISSUE TITLE
The host name for the media services host should be sul-mediaserver-xxx

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/digital_stacks_rails#39]
That is sul-mediaserver-prod not sul-wowza-prod. We should not name it after a specific component du jour, any more than we would have named imageserver after djatoka.

**Comment by ndushay** [comment]
Filed SAR-3151.

**Comment by ndushay** [comment]
and ... per SAR-3151, this has been done.

"Name sul-wowza-prod
Aliases sul-mediaserver-prod, sul-mediaserver, sul-wowza

Name sul-wowza-dev
Aliases sul-mediaserver-dev

Name sul-wowza-stage
Aliases sul-mediaserver-stage  "
