### ISSUE TITLE
remove VCR and webmock to lower maint costs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/digital_stacks_rails#40]
possibly only used for calls to purl - could use mocks instead.

**Comment by jmartin-sul** [comment]
:+1: from me, because:
* it'd be a good way to get more familiar with the code base.
* it'd make the tests less fragile.
* i have an aversion to VCR usage (see above).

**Comment by jmartin-sul** [comment]
webmock bothers me less since expectations have to be more explicit than with VCR, but i'd still prefer to get rid of it if possible and replace its usage with better non-webmock mocking.
