### ISSUE TITLE
ensure media (and other) filenames work with special chars

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/digital_stacks_rails#49]
utf-8 chars, spaces, etc.  

Are they properly url encoded in redirects to wowza server?

ditto for encrypted stacks tokens

related to sul-dlss/dlss-wowza#9

See https://github.com/sul-dlss/media/wiki/Examples-of-files-deposited-by-ETD-users,-special-characters-and-media-files  for examples.

**Comment by peetucket** [comment]
I believe stacks should work with space filenames - i ran into this issue several years ago with images for Revs and i think we fixed it (i.e. files with spaces in it should be served up by the stacks...though that was in the "old stacks code)

**Comment by ndushay** [comment]
ensure that roundtrip of   stacks-redirect --> wowza --> stacks token verification -->  user   works for weird chars in filenames

**Comment by jkeck** [comment]
FWIW, the `MediaController` uses the same routing mechanism as file/image, so if we support the URLs for downloading files in existing published PURLs, then they should already be supported on the digital stacks side.

We will want to ensure that the Wowza plugin  properly decodes/encodes the URLs that it receives/sends-out, but this should already be 👌 in stacks.

Any issues that come up would have already been issues with downloading the files (which I'm sure we would have heard about by now).

**Comment by jmartin-sul** [comment]
@jkeck suggested during standup that if we wanted to test this, we could test it in the media controller routing spec

**Comment by ndushay** [comment]
just for the record, @jkeck's comment of over 3 weeks ago was incorrect -- the routing for the media controller used diff constraints for filenames, so this really was necessary work.

Furthermore, if seemed no one knew the allowed charset even for non-media filenames, so various tickets have been spawned to pursue that.
