### ISSUE TITLE
Specify approved  locations for rights in the Digital Stacks

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/digital_stacks_rails#50]
Referencing https://github.com/sul-dlss/media/issues/55. Locations can be named in rightsMetadata to restrict access to specific machines. The named locations in rightsMetadata will be defined in Stacks as part of its implementation. Currently the definition includes

- **id** - identifier specified in a rightsMetadata \<location> element
- **name** - possible name to accompany ID, if the UI has a requirement to construct an "Available only at..."message in Embed.
- **whitelisted hosts** -- IP-addresses or host names, in full or patterns, or some combination TBD. Only sessions coming from such identified machines are authorized for access.

**Comment by ndushay** [comment]
@LynnMcRae is there a list ready somewhere?  I recall a link to a consul page or something -- can that be included here?

**Comment by ndushay** [comment]
Lynn has the info for SPEC; Hannah needs to get it for ARS;   developer needs to add it to the configs for prod
