### ISSUE TITLE
Implement location-based restrictions in Digital Stacks

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/digital_stacks_rails#51]
Referencing https://github.com/sul-dlss/media/issues/55.

The Stacks must take the rights information from dor-rights-auth that include location-based restrictions and determine if a request for a resource is from a blessed IP address or host per mapping rules that use the information from #50.

**Comment by ndushay** [comment]
Much progress has been made.  Still needing attention:  adjusting the `media_controller` method  `#json_for_media_auth`.  

There are basic pieces ready:
* dor-rights-auth  branch
* digital_stacks_rails branch

may need sul-embed piece, too???

**Comment by jmartin-sul** [comment]
i believe there is still sul-embed UI refinement to be done (sul-dlss/sul-embed#584).  but the digital_stacks_rails and dor-rights-auth parts appear to be finished, so closing this for now.
