### ISSUE TITLE
Investigate safety of using ActionDisplay#remote_ip

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/digital_stacks_rails#52]
We need to ensure there is a proxy in front of stacks that sets the appropriate headers if we want to safely use `ActionDisplay#remote_ip`.

See http://apidock.com/rails/ActionDispatch/RemoteIp

We want to make sure the user isn't setting the header themselves, presumably by having either a proxy or the rails app itself ensure that the header is kosher.   With the load balancer in front of stacks, we need to make sure we do this in the right place.

load balancer is https service for stacks:  it decrypts the user request and then re-encrypts it to send it over https to the stacks.

**Comment by tingulfsen** [comment]
Agreed. Also see http://blog.gingerlime.com/2012/rails-ip-spoofing-vulnerabilities-and-protection/ for a more detailed explanation.

**Comment by ndushay** [comment]
Need to talk to devops about this.   Is there anything between the request and the digital stacks rails app that is dealing with this?  @eefahy

**Comment by ndushay** [comment]
If there is no proxy already, then we need to do one of:
- set up a reverse proxy
- change code to not depend on ActionDisplay#remote_ip

**Comment by eefahy** [comment]
stacks.stanford.edu is behind a load balancer where we can do some header stuff. Hopefully we can do what we need to re: headers there?

**Comment by ndushay** [comment]
It would be awesome if the load balancer could be responsible for setting the header.  That would probably be the most efficient solution.

**Comment by ndushay** [comment]
Erin checking if load balancer is already wrapping a header with remote IP when it's re-wrapping an http request to send to a specific stacks VM.

**Comment by ndushay** [comment]
@jkeck wanna leave any info from conversation with Erin?

**Comment by ndushay** [comment]
Everything is taken care of -- it's part of default load balancer profile.
