### ISSUE TITLE
jsonp from auth_check: stacks can allow stream but not download;  location as well as stanford restricted

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/digital_stacks_rails#54]
The current implementation does not provide a way to separate "read" (i.e. stream) permissions from download permissions.   

Addressing this probably involves tweaking cancan ability class, and writing tests.  There may be a model in how the permissions work with "tile" for images.

**Comment by peetucket** [comment]
i.e. rule=no download

**Comment by ndushay** [comment]
check_auth jsonp  response only responses success or forbidden, but need nuances to tell sul-embed:

* location vs stanford only
* stream but not download

**Comment by ndushay** [comment]
considering this closed.  if there are trailing tendrils of functionality needed, another ticket should be opened.
