### ISSUE TITLE
File names with spaces appear to be failing token verification

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/digital_stacks_rails#65]
I'm not 100% sure, but spaces in filenames (which would probably be encoded as either a `+` or `%20`) seem like they might be causing tokens to fail verification (possibly due to a simple string comparison mismatch between the original unencoded file name and the URL encoded file name that is returned).

We should validate if this is the case or not, as this is just speculation.  dv738kn2168 has media w/ spaces in the file names.

**Comment by jmartin-sul** [comment]
seems like the wowza plugin should be encoding spaces differently (`+` is for space in form vars, but it should be `%20` in the URL path).  closing this in favor of sul-dlss/dlss-wowza#28.  can reopen this if it turns out there's work to be done in stacks.
