### ISSUE TITLE
Add ldap check to is_it_working - need a way to do this

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/digital_stacks_rails#69]
see https://github.com/sul-dlss/sul-directory/blob/master/config/initializers/is_it_working.rb#L10-L16

**Comment by ndushay** [comment]
Actually, this is trickier because sul-directory  has a bunch of code in the app supporting ` LdapSearch.in_organization` method.

**Comment by ndushay** [comment]
Closing this as it seems unlikely this will ultimately live in every app that uses LDAP.  If that's wrong,  we can make a new ticket once we have a way forward with this work.

**Comment by ndushay** [comment]
waiting for devops to implement a way for apps to check into LDAP functionality

**Comment by ndushay** [comment]
closing this as a solution doesn't seem to be imminent.
