### ISSUE TITLE
add honeybadger to stacks

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/digital_stacks_rails#79]
We want non-failing notifications to cause reporting.

- want to notify for unparseable durations

For a ruby example, see sul-dlss/exhibits#291

once done, remove squash

**Comment by jkeck** [comment]
Unassigning this for now.  It looks like we might have reached some sort of project limit for our account level and may want to hold off until that is resolved.

**Comment by ndushay** [comment]
NOTE:  Update DevOpsDocs when complete.
