### ISSUE TITLE
Configure Location Based Rights Locations

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/digital_stacks_rails#93]
We need to configure the locations for the location based rights, which is described [on consul](https://consul.stanford.edu/pages/viewpage.action?title=Rights+Metadata+Locations) in the `shared_configs` repository.

**Comment by ndushay** [comment]
@LynnMcRae @hannahfrost   where do we get the official list?

**Comment by jkeck** [comment]
@ndushay https://consul.stanford.edu/display/chimera/Rights+Metadata+Locations (which was linked in the Slack channel)

**Comment by ndushay** [comment]
Note remaining steps:  
- [ ] sul-dlss/shared_configs/pull/106  needs to be merged
- [ ] SAR ticket requesting the branch be cloned to the server (after the merge)
- [ ] deploy master to test (after branch is cloned to the server)

@jkeck   is the above correct?

**Comment by ndushay** [comment]
Just did the above steps;  locations officially configured for `sul-stacks-test`.   We will do production as part of production deploy, as there are other configurations that will need to be added to sul-stacks-prod shared_config.
